
target:
	@javac ./MyLZW.java
	@javac ./LZW.java
run:
	@java MyLZW - r < code.txt > codeR.lzw
	@java MyLZW +  < codeR.lzw > codeR.txt
	@java MyLZW - m < code.txt > codeM.lzw
	@java MyLZW +  < codeM.lzw > codeM.txt
	@java MyLZW - n < code.txt > codeN.lzw
	@java MyLZW +  < codeN.lzw > codeN.txt
	@java LZW - < code.txt > codeO.lzw
	@java LZW +  < codeO.lzw > codeO.txt

	@java MyLZW - r < all.tar > allR.lzw
	@java MyLZW +  < allR.lzw > allR.tar
	@java MyLZW - m < all.tar > allM.lzw
	@java MyLZW +  < allM.lzw > allM.tar
	@java MyLZW - n < all.tar > allN.lzw
	@java MyLZW +  < allN.lzw > allN.tar
	@java LZW - < all.tar > allO.lzw
	@java LZW +  < allO.lzw > allO.tar

	@java MyLZW - r < assig2.doc > assig2R.lzw
	@java MyLZW +  < assig2R.lzw > assig2R.doc
	@java MyLZW - m < assig2.doc > assig2M.lzw
	@java MyLZW +  < assig2M.lzw > assig2M.doc
	@java MyLZW - n < assig2.doc > assig2N.lzw
	@java MyLZW +  < assig2N.lzw > assig2N.doc
	@java LZW - < assig2.doc > assig2O.lzw
	@java LZW +  < assig2O.lzw > assig2O.doc

	@java MyLZW - r < bmps.tar > bmpsR.lzw
	@java MyLZW +  < bmpsR.lzw > bmpsR.tar
	@java MyLZW - m < bmps.tar > bmpsM.lzw
	@java MyLZW +  < bmpsM.lzw > bmpsM.tar
	@java MyLZW - n < bmps.tar > bmpsN.lzw
	@java MyLZW +  < bmpsN.lzw > bmpsN.tar
	@java LZW - < bmps.tar > bmpsO.lzw
	@java LZW +  < bmpsO.lzw > bmpsO.tar

	@java MyLZW - r < code2.txt > code2R.lzw
	@java MyLZW +  < code2R.lzw > code2R.txt
	@java MyLZW - m < code2.txt > code2M.lzw
	@java MyLZW +  < code2M.lzw > code2M.txt
	@java MyLZW - n < code2.txt > code2N.lzw
	@java MyLZW +  < code2N.lzw > code2N.txt
	@java LZW - < code2.txt > code2O.lzw
	@java LZW +  < code2O.lzw > code2O.txt

	@java MyLZW - r < edit.exe > editR.lzw
	@java MyLZW +  < editR.lzw > editR.exe
	@java MyLZW - m < edit.exe > editM.lzw
	@java MyLZW +  < editM.lzw > editM.exe
	@java MyLZW - n < edit.exe > editN.lzw
	@java MyLZW +  < editN.lzw > editN.exe
	@java LZW - < edit.exe > editO.lzw
	@java LZW +  < editO.lzw> editO.exe	


	@java MyLZW - r < frosty.jpg > frostyR.lzw
	@java MyLZW +  < frostyR.lzw > frostyR.jpg
	@java MyLZW - m < frosty.jpg > frostyM.lzw
	@java MyLZW +  < frostyM.lzw > frostyM.jpg
	@java MyLZW - n < frosty.jpg > frostyN.lzw
	@java MyLZW +  < frostyN.lzw > frostyN.jpg
	@java LZW - < frosty.jpg > frostyO.lzw
	@java LZW +  < frostyO.lzw > frostyO.jpg

	@java MyLZW - r < gone_fishing.bmp > gone_fishingR.lzw
	@java MyLZW +  < gone_fishingR.lzw > gone_fishingR.bmp
	@java MyLZW - m < gone_fishing.bmp > gone_fishingM.lzw
	@java MyLZW +  < gone_fishingM.lzw > gone_fishingM.bmp
	@java MyLZW - n < gone_fishing.bmp > gone_fishingN.lzw
	@java MyLZW +  < gone_fishingN.lzw > gone_fishingN.bmp
	@java LZW - < gone_fishing.bmp> gone_fishingO.lzw
	@java LZW +  < gone_fishingO.lzw > gone_fishingO.bmp

	@java MyLZW - r < large.txt > largeR.lzw
	@java MyLZW +  < largeR.lzw > largeR.txt
	@java MyLZW - m < large.txt > largeM.lzw
	@java MyLZW +  < largeM.lzw > largeM.txt
	@java MyLZW - n < large.txt > largeN.lzw
	@java MyLZW +  < largeN.lzw > largeN.txt
	@java LZW - < large.txt > largeO.lzw
	@java LZW +  < largeO.lzw > largeO.txt

	@java MyLZW - r < Lego-big.gif > Lego-bigR.lzw
	@java MyLZW +  < Lego-bigR.lzw> Lego-bigR.gif
	@java MyLZW - m < Lego-big.gif > Lego-bigM.lzw
	@java MyLZW +  < Lego-bigM.lzw> Lego-bigM.gif
	@java MyLZW - n < Lego-big.gif > Lego-bigN.lzw
	@java MyLZW +  < Lego-bigN.lzw> Lego-bigN.gif
	@java LZW - < Lego-big.gif > Lego-bigO.lzw
	@java LZW +  < Lego-bigO.lzw > Lego-bigO.gif

	@java MyLZW - r < medium.txt > mediumR.lzw
	@java MyLZW +  < mediumR.lzw> mediumR.txt
	@java MyLZW - m < medium.txt > mediumM.lzw
	@java MyLZW +  < mediumM.lzw> mediumM.txt
	@java MyLZW - n < medium.txt > mediumN.lzw
	@java MyLZW +  < mediumN.lzw> mediumN.txt
	@java LZW - < medium.txt > mediumO.lzw
	@java LZW +  < mediumO.lzw> mediumO.txt

	@java MyLZW - r < texts.tar > textsR.lzw
	@java MyLZW +  < textsR.lzw > textsR.tar
	@java MyLZW - m < texts.tar > textsM.lzw
	@java MyLZW +  < textsM.lzw > textsM.tar
	@java MyLZW - n < texts.tar > textsN.lzw
	@java MyLZW +  < textsN.lzw > textsN.tar
	@java LZW - < texts.tar > textsO.lzw
	@java LZW + < textsO.lzw > textsO.tar

	@java MyLZW - r < wacky.bmp> wackyR.lzw
	@java MyLZW +  < wackyR.lzw > wackyR.bmp
	@java MyLZW - m < wacky.bmp> wackyM.lzw
	@java MyLZW +  < wackyM.lzw > wackyM.bmp
	@java MyLZW - n < wacky.bmp> wackyN.lzw
	@java MyLZW +  < wackyN.lzw > wackyN.bmp
	@java LZW - < wacky.bmp> wackyO.lzw
	@java LZW + < wackyO.lzw > wackyO.bmp

	@java MyLZW - r < winnt256.bmp> winnt256R.lzw
	@java MyLZW + < winnt256R.lzw> winnt256R.bmp
	@java MyLZW - m < winnt256.bmp> winnt256M.lzw
	@java MyLZW + < winnt256M.lzw> winnt256M.bmp
	@java MyLZW - n < winnt256.bmp> winnt256N.lzw
	@java MyLZW + < winnt256N.lzw> winnt256N.bmp
	@java LZW - < winnt256.bmp> winnt256O.lzw
	@java LZW + < winnt256O.lzw> winnt256O.bmp

clean:
	@ -rm *.class
	@ -rm *.lzw
	@ -rm *.bmp
	@ -rm *.tar
	@ -rm *.gif
	@ -rm *.txt
	@ -rm *.doc
	@ -rm *.exe
	@ -rm *.jpg
